### PR TITLE
launch path is now the root

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
currently it's set to berbaquero.github.com/reeddit/ actually in the store that's why I went in to change stuff because I was getting a bar accross the top from the redirect

**Comment by berbaquero** [comment]
Hmm, now it doesn't seem to work from FFOS :O - I'm gonna revert the launch path, then.

**Comment by cheeaun** [comment]
@berbaquero you didn't list the app to be under the reedditapp.com domain? (Path to manifest.webapp, I suppose)

**Comment by berbaquero** [comment]
@cheeaun exactly - the manifest is not set to the reedditapp.com domain. Currently is in berbaquero.github.com/reeddit/manifest.webapp, and it's being redirected to berbaquero.com/reeddit/manifest.webapp, apparently.

But I'm not sure you can even change the manifest URL after the app has been verified.

**Comment by cheeaun** [comment]
@berbaquero you'll need to email the App Reviews guys. It's stated there when you try to change the Manifest URL in the Edit Listing page.

**Comment by calvinmetcalf** [comment]
I think what you need to do is rename the repo for your website to something like berbaquero/website and what is at the current master branch needs to move the the gh-pages branch.   if you have a custom domain for your website made via username/username.github.io repo it then redirects for ALL your repo gh-pages

**Comment by calvinmetcalf** [comment]
or what @cheeaun said

**Comment by berbaquero** [comment]
Yeah, I guess I'll send an email to the Marketplace guys to change the manifest URL to reedditapp.com.

I tested installing the wep-app with the current config and it has worked fine on my end - FFOS emulator and installing from FF on Mac - are you still having troubles in your side, Calvin?

**Pull request merged**
