### PR TITLE
Additional site preview support.

### PR DESCRIPTION
**Pull request by JasonGhent**
- Preview added for livememe and youtube

### CODE REVIEW

**Comment by berbaquero** [comment]
Hey, awesome! Thanks. :)

I will test this later today, and merge when everything's fine.

Did you try the YouTube previewing on mobile devices?

**Comment by JasonGhent** [comment]
I did try it on mobile on Firefox for Android and Chrome. I'm also working on some fixes to the nature of scrolling on Firefox for Android. I'll keep in touch with any success I have for making it more scroll responsive.

**Comment by berbaquero** [comment]
Hey Jason.

As you can see, I merged your PR, but after trying and testing the YouTube previewing, I decided to remove it (at least temporarily) — I saw and realized **how much _stuff_** is being loaded within the YouTube `iframe` and I think it's better if I leave it out. It just doesn't feel right to me at the moment.

Your PR actually reminded to remove the quickmeme checking in the image previewing, as quickmeme has been banned from reddit for a while now. The livememe support is working nicely, so thanks for that.

And thanks again for collaborating! :)

**Comment by berbaquero** [comment]
FWIW, before removing the YouTube previewing, I checked http://embedresponsively.com/ for a responsive YouTube embed solution with only CSS, and also modified the `RegEx`, as the one submitted in your PR had some issues with `youtube.com` format URLs (the `youtu.be` ones worked fine).

Here's the Gist, if you want to take a look and maybe use it for your fork: https://gist.github.com/berbaquero/db005b178ebd544f8c70 — :)

**Pull request merged**
